export interface Pcinfo{
    _id?: number,
    number?: number,
    name: string,
    date: string,
    city: string,
    phone: string,
    purchasePrice: number,
    salePrice: number,
    quantity : number,
    totalP : number,
    modePayement : string,
    status: string,
    isConfirmed: boolean,
    cancellationReason?: string,
    orderDetails?: any,
    deliveryManId?: string,
    societeCode: string,
}
